name: Release

on:
  push:
    tags: [v*]

permissions:
  contents: write

env:
  CARGO_TERM_COLOR: always

jobs:
  create-release:
    runs-on: ubuntu-20.04
    outputs:
      tag: ${{ steps.create-gh-release.outputs.computed-prefix }}${{ steps.create-gh-release.outputs.version }}
    steps:
      - uses: actions/checkout@v3
      - id: create-gh-release
        uses: taiki-e/create-gh-release-action@v1
        with:
          draft: true
          token: ${{ secrets.GITHUB_TOKEN }}

  upload-examples:
    needs: create-release
    runs-on: ubuntu-20.04
    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v3
      - name: Copy and upload examples
        run: |
          ./scripts/make_examples_bundle.sh
          gh release upload ${{ needs.create-release.outputs.tag }} tmp/examples.zip

  build-app:
    needs: create-release
    strategy:
      matrix:
        include:
          - os: ubuntu-20.04
            target: x86_64-unknown-linux-gnu
            exe_name: ambient
          - os: macos-latest
            target: aarch64-apple-darwin
            exe_name: ambient
          - os: windows-latest
            target: x86_64-pc-windows-msvc
            exe_name: ambient.exe
    runs-on: ${{ matrix.os }}
    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      EXE_DIR: target/${{ matrix.target }}/release
    steps:
      - uses: actions/checkout@v3
      - name: Install build dependencies
        if: matrix.os == 'ubuntu-20.04'
        run: |
          sudo apt-get update
          sudo apt-get install --no-install-recommends -y libasound2-dev libglib2.0-dev libxcb-shape0-dev libxcb-xfixes0-dev \
            libcairo-dev libgtk2.0-dev libsoup2.4-dev libgtk-3-dev libwebkit2gtk-4.0-dev xorg-dev ninja-build libxcb-render0-dev
      - name: Install aarch64-apple-darwin
        if: matrix.target == 'aarch64-apple-darwin'
        run: rustup target add aarch64-apple-darwin
      - uses: dtolnay/rust-toolchain@stable
      # We don't do caching here because we only have 10gb and they'll be occupied by normal builds all the time anyway
      - name: Build
        run: cargo build --release -p ambient --target ${{ matrix.target }}
      - name: Install certificate (OSX)
        if: matrix.os == 'macos-latest'
        uses: apple-actions/import-codesign-certs@v1
        with:
          p12-file-base64: ${{ secrets.MACOS_CERTIFICATE }}
          p12-password: ${{ secrets.MACOS_CERTIFICATE_PWD }}
      - name: Codesign executable (OSX)
        if: matrix.os == 'macos-latest'
        run: /usr/bin/codesign --force -s ${{ secrets.MAC_CODESIGN }} --options=runtime --entitlements app/osx_entitlements.xml --deep ${{ env.EXE_DIR }}/${{ matrix.exe_name }} -v
      - name: Bundle
        uses: thedoctor0/zip-release@0.7.1
        with:
          type: "zip"
          filename: ambient-${{ matrix.target }}.zip
          directory: ${{ env.EXE_DIR }}
          path: ${{ matrix.exe_name }}
      - name: Notarize app bundle (OSX)
        if: matrix.os == 'macos-latest'
        run: |
          cd ${{ env.EXE_DIR }}
          xcrun notarytool store-credentials "notarytool-profile" --apple-id "${{ secrets.APPLE_DEVELOPER_EMAIL }}" --team-id="${{ secrets.APPLE_TEAM_ID }}" --password "${{ secrets.APPLE_DEVELOPER_PASSWORD }}"
          xcrun notarytool submit "ambient-${{ matrix.target }}.zip" --keychain-profile "notarytool-profile" --wait
      - name: Upload
        run: gh release upload ${{ needs.create-release.outputs.tag }} ${{ env.EXE_DIR }}/ambient-${{ matrix.target }}.zip

  publish-api:
    needs: [create-release, build-app]
    runs-on: ubuntu-20.04
    env:
      CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}
    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@stable
      - run: cd guest/rust/api/api_macros && cargo publish
      - run: cd guest/rust/api && cargo publish

  publish-release:
    needs: [create-release, build-app, publish-api]
    runs-on: ubuntu-20.04
    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v3
      - name: mark release as non-draft
        run: gh release edit ${{ needs.create-release.outputs.tag }} --draft=false
